# Register a user
POST http://localhost:5000/api/users/
Content-Type: application/json

{
  "name": "Steve Smith",
  "email": "steve@example.com",
  "password": "123456"
}

###

GET http://localhost:5000/api/users/profile/5cdac0fd4d70642420959301
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWNjY2ZiNWZlZjQ0MzIxN2RjN2MxM2M0In0sImlhdCI6MTU1NjkzNzU2NywiZXhwIjoxNTU3Mjk3NTY3fQ.gKgkc3QMsri6c2C_ClhKfN9fO8Ekv5r04i7P_jMV0Ic

