# Register a user
POST http://localhost:5000/api/users/
Content-Type: application/json

{
  "name": "Steve Smith",
  "email": "steve@example.com",
  "password": "123456"
}

###

GET http://localhost:5000/api/users/5cdac0fd4d70642420959301
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWNkYWMwZmQ0ZDcwNjQyNDIwOTU5MzAxIn0sImlhdCI6MTU1Nzg0MzcxMywiZXhwIjoxNTU4MjAzNzEzfQ.0H647cPYAtk9RT7zGTlbWNQQ4Fqy9YhTcShTnuo6-Pg

###

GET http://localhost:5000/api/users/profile/me
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWNkYWMwZmQ0ZDcwNjQyNDIwOTU5MzAxIn0sImlhdCI6MTU1Nzg0MzcxMywiZXhwIjoxNTU4MjAzNzEzfQ.0H647cPYAtk9RT7zGTlbWNQQ4Fqy9YhTcShTnuo6-Pg

